import * as THREE from 'https://unpkg.com/three@0.165.0/build/three.module.js';

const ui = Object.fromEntries(['hud','start-screen','game-over','settings-screen','loading','score','best','speed','speed-fill','final-score','run-message','launch','restart','menu','colours','shield-indicator','magnet-indicator','boost-indicator','settings-button','close-settings','audio-toggle','music-toggle','vibration-toggle'].map(id => [id, document.getElementById(id)]));
const palette = ['#35eaff','#ff4b78','#ffc345','#a778ff','#6aff99'];
let selectedColour = palette[0];
palette.forEach((colour, index) => { const button = document.createElement('button'); button.className = `swatch ${index === 0 ? 'selected' : ''}`; button.style.background = colour; button.style.color = colour; button.title = `Select ${colour}`; button.addEventListener('click', () => { selectedColour = colour; document.querySelectorAll('.swatch').forEach(s => s.classList.remove('selected')); button.classList.add('selected'); }); ui.colours.append(button); });

const scene = new THREE.Scene(); scene.fog = new THREE.FogExp2(0x8bc8ff, .0035); scene.background = new THREE.Color(0x78baf2);
const camera = new THREE.PerspectiveCamera(65, innerWidth / innerHeight, .1, 1800); const renderer = new THREE.WebGLRenderer({antialias:true}); renderer.setSize(innerWidth, innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; document.body.prepend(renderer.domElement);
const world = new THREE.Group(); scene.add(world); scene.add(new THREE.HemisphereLight(0xd7efff, 0x394c9d, 2.3)); const sun = new THREE.DirectionalLight(0xfff2d3, 2.8); sun.position.set(-80,100,-90); sun.castShadow = true; scene.add(sun);
const laneCenters = [-10,0,10]; const keys = {}; let laneIndex = 1, laneLean = 0; addEventListener('keydown', e => { keys[e.code] = true; if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)) e.preventDefault(); if(!e.repeat && active && (e.code==='KeyA'||e.code==='ArrowLeft'||e.code==='KeyD'||e.code==='ArrowRight')) changeLane(e.code==='KeyA'||e.code==='ArrowLeft' ? -1 : 1); }); addEventListener('keyup', e => keys[e.code] = false);
let car, carGlow, roadLines, active = false, last = 0, score = 0, speed = 12, elapsed = 0, spawnClock = 0, difficulty = 1, shield = 0, magnet = 0, boost = 0, best = Number(localStorage.skyRushBest || 0); let coins = [], obstacles = [], pickups = [], particles = []; let audioEnabled = localStorage.skyRushAudio !== 'off', musicEnabled = localStorage.skyRushMusic !== 'off', vibrationEnabled = localStorage.skyRushVibration !== 'off', audioContext, musicTimer;
const materials = { coin:new THREE.MeshStandardMaterial({color:0xffbd39, emissive:0xa95b00, emissiveIntensity:1.5, metalness:.75, roughness:.18}), obstacle:new THREE.MeshStandardMaterial({color:0x3c326d, emissive:0x35206a, emissiveIntensity:.45, metalness:.3, roughness:.4}) };
function buildRoadWorld(){
  const asphalt=new THREE.MeshStandardMaterial({color:0x15182b,roughness:.9,metalness:.08}); const concrete=new THREE.MeshStandardMaterial({color:0x383f58,roughness:.72,metalness:.15}); const rail=new THREE.MeshStandardMaterial({color:0x20355b,metalness:.8,roughness:.22,emissive:0x09132c,emissiveIntensity:.4}); const neon=new THREE.MeshStandardMaterial({color:0x4df5ff,emissive:0x24b5df,emissiveIntensity:2.3,metalness:.35});
  const road=new THREE.Mesh(new THREE.PlaneGeometry(30,6000),asphalt);road.rotation.x=-Math.PI/2;road.position.set(0,0,-2950);road.receiveShadow=true;world.add(road);
  const shoulder=new THREE.Mesh(new THREE.PlaneGeometry(42,6000),concrete);shoulder.rotation.x=-Math.PI/2;shoulder.position.set(0,-.025,-2950);shoulder.receiveShadow=true;world.add(shoulder);
  for(let z=0;z>-5950;z-=14){ for(const x of [-5,5]){ const mark=new THREE.Mesh(new THREE.BoxGeometry(.25,.035,6),new THREE.MeshBasicMaterial({color:0xffd96a}));mark.position.set(x,.02,z);world.add(mark); } if(z%56===0){ for(const side of [-1,1]){ const post=new THREE.Mesh(new THREE.BoxGeometry(.26,2.2,.26),rail);post.position.set(side*16,1.1,z);world.add(post); const strip=new THREE.Mesh(new THREE.BoxGeometry(.11,.11,12),neon);strip.position.set(side*15.75,1.75,z);world.add(strip); } } }
  for(const side of [-1,1]){ const barrier=new THREE.Mesh(new THREE.BoxGeometry(.65,.72,6000),rail);barrier.position.set(side*14.9,.36,-2950);barrier.castShadow=true;world.add(barrier); }
  for(let z=-45;z>-5950;z-=55){ for(const side of [-1,1]){ const tower=new THREE.Mesh(new THREE.BoxGeometry(9+Math.random()*7,12+Math.random()*34,12+Math.random()*15),concrete);tower.position.set(side*(45+Math.random()*26),tower.geometry.parameters.height/2,z-Math.random()*18);tower.castShadow=true;world.add(tower); const windowBand=new THREE.Mesh(new THREE.BoxGeometry(tower.geometry.parameters.width+.04,.26,tower.geometry.parameters.depth+.04),neon);windowBand.position.set(tower.position.x,tower.position.y+2,tower.position.z);world.add(windowBand); } }
}
buildRoadWorld();
const stars = new THREE.Points(new THREE.BufferGeometry(), new THREE.PointsMaterial({color:0xe4f6ff,size:1.4,transparent:true,opacity:.58})); const positions=[]; for(let i=0;i<450;i++) positions.push((Math.random()-.5)*700,Math.random()*300-30,-Math.random()*1800); stars.geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3)); scene.add(stars);
function buildCar(){ car = new THREE.Group(); const paint = new THREE.MeshStandardMaterial({color:selectedColour,metalness:.6,roughness:.22,emissive:selectedColour,emissiveIntensity:.13}); const dark = new THREE.MeshStandardMaterial({color:0x080b17,metalness:.85,roughness:.14}); const tyre = new THREE.MeshStandardMaterial({color:0x06070c,roughness:.8}); const rim = new THREE.MeshStandardMaterial({color:0x96eaff,emissive:0x2266aa,emissiveIntensity:1.4,metalness:.85}); const body = new THREE.Mesh(new THREE.BoxGeometry(3.1,.6,5.25),paint); body.position.y=.85; body.castShadow=true; car.add(body); const hood = new THREE.Mesh(new THREE.BoxGeometry(2.82,.22,1.45),paint);hood.position.set(0,1.2,-1.7);hood.rotation.x=-.08;car.add(hood); const cabin = new THREE.Mesh(new THREE.BoxGeometry(2.25,.76,2.25),dark); cabin.position.set(0,1.48,.22); cabin.rotation.x=-.13; car.add(cabin); [-1,1].forEach(x=>[-1,1].forEach(z=>{const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.53,.53,.34,16),tyre);wheel.rotation.z=Math.PI/2;wheel.position.set(x*1.6,.55,z*1.62);wheel.castShadow=true;car.add(wheel);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.24,.24,.36,12),rim);hub.rotation.z=Math.PI/2;hub.position.set(x*1.6,.55,z*1.62);car.add(hub);})); const spoiler=new THREE.Mesh(new THREE.BoxGeometry(3.15,.12,.35),dark);spoiler.position.set(0,1.48,2.33);car.add(spoiler); carGlow=new THREE.PointLight(selectedColour,3.5,18);carGlow.position.set(0,.8,2.8);car.add(carGlow); const lightMat=new THREE.MeshBasicMaterial({color:0x8ff7ff}); [-.78,.78].forEach(x=>{let l=new THREE.Mesh(new THREE.BoxGeometry(.42,.14,.12),lightMat);l.position.set(x,1.08,-2.7);car.add(l);}); car.position.set(0,.02,5); world.add(car); }
function ring(position, type='coin'){ const group=new THREE.Group(); const isCoin=type==='coin'; const mesh = new THREE.Mesh(new THREE.TorusGeometry(isCoin?.52:.72,isCoin?.14:.15,10,18), isCoin?materials.coin:new THREE.MeshStandardMaterial({color:type==='shield'?0x75ddff:type==='magnet'?0xea76ff:0xff654d,emissive:type==='shield'?0x1679ff:type==='magnet'?0xa20aff:0xd21c21,emissiveIntensity:1.4,metalness:.5})); mesh.rotation.y=Math.PI/2; group.add(mesh); if(!isCoin){const glyph=new THREE.Sprite(new THREE.SpriteMaterial({map:makeLabel(type),transparent:true})); glyph.scale.set(1.6,1.6,1); group.add(glyph);} group.position.copy(position); world.add(group); return group; }
function makeLabel(type){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle='white';x.font='bold 62px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(type==='shield'?'✦':type==='magnet'?'◎':'➜',64,64);return new THREE.CanvasTexture(c);}
function obstacle(position){ const g=new THREE.Group(); const core=new THREE.Mesh(new THREE.BoxGeometry(2.6,2.5,1.15),materials.obstacle);core.castShadow=true;g.add(core); const warning=new THREE.Mesh(new THREE.BoxGeometry(2.67,.22,1.2),new THREE.MeshBasicMaterial({color:0xff5370}));warning.position.y=.55;g.add(warning); const halo=new THREE.Mesh(new THREE.TorusGeometry(1.4,.08,8,18),new THREE.MeshBasicMaterial({color:0xca8dff}));halo.rotation.x=Math.PI/2;halo.position.y=1.1;g.add(halo);g.position.copy(position);world.add(g);return g;}
function burst(pos, colour, count=16){for(let i=0;i<count;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.08+Math.random()*.12,5,5),new THREE.MeshBasicMaterial({color:colour}));p.position.copy(pos);p.userData={v:new THREE.Vector3((Math.random()-.5)*10,(Math.random()-.5)*10,(Math.random()-.5)*10),life:.45+Math.random()*.45};world.add(p);particles.push(p)}}
function clearObjects(){[...coins,...obstacles,...pickups,...particles].forEach(o=>world.remove(o));coins=[];obstacles=[];pickups=[];particles=[];}
function lane(){ return laneCenters[Math.floor(Math.random()*laneCenters.length)]; }
function reset(){ clearObjects(); if(car)world.remove(car); laneIndex=1; laneLean=0; buildCar(); score=0; speed=12;elapsed=0;spawnClock=0;difficulty=1;shield=magnet=boost=0; for(let z=-20;z>-390;z-=16){if(Math.random()<.8) coins.push(ring(new THREE.Vector3(lane(),1.35,z))); if(Math.random()<.16) obstacles.push(obstacle(new THREE.Vector3(lane(),1.28,z-7)));} updateHUD(); }
function start(){ reset(); active=true; ensureAudio(); if(musicEnabled) startMusic(); ui['start-screen'].classList.add('hidden');ui['game-over'].classList.add('hidden');ui.hud.classList.remove('hidden'); }
function end(){ active=false; ui.hud.classList.add('hidden'); ui['final-score'].textContent=String(score).padStart(3,'0'); const newBest=score>best;if(newBest){best=score;localStorage.skyRushBest=best;}ui['run-message'].textContent=newBest?'NEW SKYWAY RECORD!':score>25?'A fierce run through the traffic.': 'The skyway always demands another run.';ui['game-over'].classList.remove('hidden'); }
function spawnAhead(){const z=car.position.z-150-Math.random()*110; const x=lane();const y=1.35; if(Math.random()<.59){coins.push(ring(new THREE.Vector3(x,y,z))); if(Math.random()<.28)coins.push(ring(new THREE.Vector3(x,y,z-3)));} else obstacles.push(obstacle(new THREE.Vector3(x,1.28,z))); if(Math.random()<.07)pickups.push(ring(new THREE.Vector3(x,y,z-5), ['shield','magnet','boost'][Math.floor(Math.random()*3)]));}
function activate(type){if(type==='shield')shield=8;if(type==='magnet')magnet=9;if(type==='boost')boost=5;}
function changeLane(direction){ const next=THREE.MathUtils.clamp(laneIndex+direction,0,laneCenters.length-1);if(next===laneIndex)return;laneIndex=next;laneLean=direction;sfx('lane');buzz(14,.25);}
function ensureAudio(){if(!audioContext)audioContext=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();}
function tone(freq,duration=.09,volume=.05,wave='sine'){if(!audioContext)return;const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type=wave;osc.frequency.value=freq;gain.gain.setValueAtTime(volume,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+duration);osc.connect(gain).connect(audioContext.destination);osc.start();osc.stop(audioContext.currentTime+duration);}
function sfx(type){if(!audioEnabled)return;ensureAudio();if(type==='coin')tone(880,.08,.06,'triangle');if(type==='lane')tone(340,.06,.035,'square');if(type==='power')tone(570,.16,.06,'sine');if(type==='crash')tone(90,.35,.12,'sawtooth');}
function startMusic(){if(!musicEnabled||musicTimer)return;ensureAudio();const notes=[220,277,330,277,247,294,370,294];let step=0;musicTimer=setInterval(()=>{if(active&&musicEnabled)tone(notes[step++%notes.length],.16,.018,'sine');},260);}
function stopMusic(){clearInterval(musicTimer);musicTimer=undefined;}
function buzz(duration=18,intensity=.2){if(!vibrationEnabled)return;if(navigator.vibrate)navigator.vibrate(duration);for(const pad of navigator.getGamepads?.()||[]){pad?.vibrationActuator?.playEffect?.('dual-rumble',{duration,startDelay:0,weakMagnitude:intensity,strongMagnitude:intensity}).catch(()=>{});}}
function syncSettings(){[['audio-toggle',audioEnabled],['music-toggle',musicEnabled],['vibration-toggle',vibrationEnabled]].forEach(([id,on])=>{ui[id].textContent=on?'ON':'OFF';ui[id].classList.toggle('on',on);ui[id].setAttribute('aria-pressed',String(on));});}
function dist(a,b){return a.position.distanceToSquared(b.position)}
function updateHUD(){ui.score.textContent=String(score).padStart(3,'0');ui.best.textContent=`BEST ${String(best).padStart(3,'0')}`;ui.speed.textContent=String(Math.round(speed*13)).padStart(3,'0');ui['speed-fill'].style.width=`${Math.min(100,speed/47*100)}%`;[['shield',shield],['magnet',magnet],['boost',boost]].forEach(([name,time])=>{const e=ui[`${name}-indicator`];e.classList.toggle('hidden',time<=0);e.querySelector('b').textContent=`${time.toFixed(1)}s`;});}
function tick(dt){ if(!active){renderer.render(scene,camera);return;} elapsed+=dt;difficulty=1+Math.floor(score/12)*.14; const throttle=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0); const max=boost>0?50:34; speed=THREE.MathUtils.damp(speed, throttle>0?max:throttle<0?7:14,3,dt);car.position.x=THREE.MathUtils.damp(car.position.x,laneCenters[laneIndex],13,dt);laneLean=THREE.MathUtils.damp(laneLean,0,7,dt);car.position.y=.02;car.position.z-=speed*dt;car.rotation.z=THREE.MathUtils.damp(car.rotation.z,-laneLean*.22,10,dt);car.rotation.x=THREE.MathUtils.damp(car.rotation.x,0,7,dt);car.rotation.y=THREE.MathUtils.damp(car.rotation.y,-laneLean*.08,10,dt);
 shield=Math.max(0,shield-dt);magnet=Math.max(0,magnet-dt);boost=Math.max(0,boost-dt); spawnClock+=dt;if(spawnClock>Math.max(.5,1.25-difficulty*.12)){spawnClock=0;spawnAhead();} const target=new THREE.Vector3(car.position.x*.28,6.5,car.position.z+17);camera.position.lerp(target,1-Math.exp(-dt*3.3));camera.lookAt(car.position.x*.16,1.2,car.position.z-28);
 coins.forEach((c,i)=>{c.rotation.z+=dt*3;const d=dist(c,car);if(magnet>0&&d<120){c.position.lerp(car.position,.09);}if(d<4.1){score++;sfx('coin');buzz(10,.12);burst(c.position,0xffc13d,10);world.remove(c);coins.splice(i,1);}}); obstacles.forEach((o,i)=>{o.rotation.y+=dt*1.5;if(dist(o,car)<7.4){if(shield>0){shield=0;sfx('power');buzz(30,.55);burst(o.position,0x7bdbff,28);world.remove(o);obstacles.splice(i,1);}else{sfx('crash');buzz(160,.9);end();}}});pickups.forEach((p,i)=>{p.rotation.z+=dt*2.5;if(dist(p,car)<5){const type=p.children[1]?.material.map.image ? ({'✦':'shield','◎':'magnet','➜':'boost'}) : {}; const hue=p.children[0].material.color.getHex();activate(hue===0x75ddff?'shield':hue===0xea76ff?'magnet':'boost');sfx('power');buzz(30,.4);burst(p.position,hue,18);world.remove(p);pickups.splice(i,1);}});particles.forEach((p,i)=>{p.position.addScaledVector(p.userData.v,dt);p.userData.life-=dt;p.material.opacity=Math.max(0,p.userData.life*1.4);if(p.userData.life<=0){world.remove(p);particles.splice(i,1);}});[coins,obstacles,pickups].forEach(list=>list.forEach((o,i)=>{if(o.position.z>car.position.z+30){world.remove(o);list.splice(i,1);}})); updateHUD();renderer.render(scene,camera); }
function frame(t){const dt=Math.min((t-last)/1000||0,.05);last=t;tick(dt);requestAnimationFrame(frame);} addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});ui.launch.onclick=start;ui.restart.onclick=start;ui.menu.onclick=()=>{stopMusic();ui['game-over'].classList.add('hidden');ui['start-screen'].classList.remove('hidden');};ui['settings-button'].onclick=()=>{syncSettings();ui['settings-screen'].classList.remove('hidden');};ui['close-settings'].onclick=()=>ui['settings-screen'].classList.add('hidden');ui['audio-toggle'].onclick=()=>{audioEnabled=!audioEnabled;localStorage.skyRushAudio=audioEnabled?'on':'off';syncSettings();};ui['music-toggle'].onclick=()=>{musicEnabled=!musicEnabled;localStorage.skyRushMusic=musicEnabled?'on':'off';if(musicEnabled)startMusic();else stopMusic();syncSettings();};ui['vibration-toggle'].onclick=()=>{vibrationEnabled=!vibrationEnabled;localStorage.skyRushVibration=vibrationEnabled?'on':'off';syncSettings();};syncSettings();ui.loading.classList.add('hidden');requestAnimationFrame(frame);
